### ISSUE TITLE
modules for 4.4.87-gnu

### ISSUE THREAD

**Issue by twotwenty** [gnubee-git/gnubee-git.github.io#1]
extracted the modules to /lib/modules/4.4.87-gnu/
not really sure how to get the modules to load 
I really need BTRFS when I try to load them it lacks 
modprobe btrfs results in
```
modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.87-gnu/modules.dep.bin'

```

**Comment by dgazineu** [comment]
"depmod -a" should create the required files to load the module

Em 8 de dez de 2017 18:11, "Two" <notifications@github.com> escreveu:
